App\Form\Model\ProfileDto:
    properties:
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        address:
            - NotBlank: ~
        country:
            - NotBlank: ~
        locality:
            - NotBlank: ~